backend/registry/api/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'people', views.PersonViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'licenses', views.LicenseViewSet)
router.register(r'person-roles', views.PersonRoleViewSet)
router.register(r'resource-kinds', views.ResourceKindViewSet, basename='resourcekind')
router.register(r'resource-statuses', views.ResourceStatusViewSet)
router.register(r'resources', views.ResourceViewSet)
router.register(r'resource-files', views.ResourceFileViewSet)

urlpatterns = [
    path('docs/', views.docs, name='api_docs'),
    path('', include(router.urls)),
]

backend/registry/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('people/', views.people, name='people'),
    path('people/<slug:person_id>/', views.person, name='person'),
    path('organisations/', views.organisations, name='organisations'),
    path('organisations/<slug:organisation_id>/', views.organisation, name='organisation'),
    path('groups/', views.groups, name='groups'),
    path('groups/<slug:group_id>/', views.group, name='group'),
    path('licenses/', views.licenses, name='licenses'),
    path('licenses/<slug:license_id>/', views.license, name='license'),
    path('resources/', views.resources, name='resources'),
    path('resources/add/', views.resource_add, name='resource_add'),
    path('resources/<slug:resource_id>/', views.resource, name='resource'),
    path('resources/<slug:resource_id>/edit/', views.resource_edit, name='resource_edit'),
    path('study-designs/', views.study_designs, name='study_designs'),
    path('study-designs/add/', views.study_design_add, name='study_design_add'),
    path('study-designs/<slug:study_design_id>/', views.study_design, name='study_design'),
    path('study-designs/<slug:study_design_id>/edit/', views.study_design_edit, name='study_design_edit'),
    path('study-designs/<slug:study_design_id>/map/', views.study_design_map, name='study_design_map'),
]

backend/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from decorator_include import decorator_include

import backend.registry.urls
import backend.registry.media
import backend.registry.consumers
from backend.auth import site_member_required, CustomPasswordResetView

admin.site.site_title = "Registry Administration"
admin.site.site_header = "Registry Administration"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('backend.registry.api.urls')),
    path('media/<path:path>', backend.registry.media.check_access),
    path('', decorator_include([login_required, site_member_required], (backend.registry.urls, 'registry'), namespace='registry')),  # type: ignore
] + debug_toolbar_urls()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websocket_urlpatterns = [
    path('ws/registry/study-design-maps/<str:study_design_id>', backend.registry.consumers.YjsConsumer.as_asgi()),  # type: ignore
]

backend/registry/models.py
import os
import shortuuid

from django.conf import settings
from django.db import models, transaction
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site

from django_countries.fields import CountryField

from backend.utils import get_current_site

UUID_LENGTH = 12


# -----------------------------------------------------------------------------
# Utils

def uuid():
    # Keep the alphabet and length in sync with the one on the frontend (studyDesignMaps/shortUUID.ts)
    su = shortuuid.ShortUUID(alphabet='23456789abcdefghjklmnpqrstuvwxyz')
    return su.random(length=UUID_LENGTH)


class BaseModel(models.Model):
    id = models.CharField(primary_key=True, max_length=UUID_LENGTH, default=uuid, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# -----------------------------------------------------------------------------
# Project

class Project(BaseModel):
    site = models.OneToOneField(Site, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    logo = models.ImageField(null=True, blank=True, upload_to='projects/logos')
    style = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['site__name']

    def __str__(self):
        return str(self.site)

    @property
    def domain(self):
        return self.site.domain

    @property
    def name(self):
        return self.site.name

    def save(self, *args, **kwargs):
        if self._state.adding:
            for (pos, type) in enumerate(settings.REGISTRY_DEFAULT_NODE_TYPES):
                StudyDesignNodeType.objects.create(
                    site=self.site,
                    name=type['name'],
                    color=type['color'],
                    description=type.get('description', ''),
                    position=pos
                )
        super().save(*args, **kwargs)


class SiteMixin(models.Model):
    site = models.ForeignKey(Site, on_delete=models.CASCADE)

    class Meta:
        abstract = True

    @classmethod
    def site_objects(cls, request):
        return cls.objects.filter(site=get_current_site(request))


class SitesMixin(models.Model):
    sites = models.ManyToManyField(Site, blank=True)

    class Meta:
        abstract = True

    @classmethod
    def site_objects(cls, request):
        return cls.objects.filter(sites=get_current_site(request))


# -----------------------------------------------------------------------------
# Licenses

class License(BaseModel, SitesMixin):
    name = models.CharField(max_length=255)
    url = models.URLField('URL', null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        if self.description:
            return f'{self.name} - {self.description}'
        else:
            return self.name


# -----------------------------------------------------------------------------
# People and groups

class Person(BaseModel, SitesMixin):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    orcid = models.CharField('ORCID Id', max_length=19, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'People'
        ordering = ['user__first_name', 'user__last_name']

    def __str__(self):
        return self.full_name

    @property
    def email(self):
        return self.user.email

    @property
    def first_name(self):
        return self.user.first_name

    @property
    def last_name(self):
        return self.user.last_name

    @property
    def full_name(self):
        return self.user.get_full_name() if self.user.get_full_name() else self.user.username

    @property
    def orcid_url(self):
        if self.orcid is not None:
            return f'https://orcid.org/{self.orcid}'
        else:
            return None


class PersonRole(BaseModel, SiteMixin):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['name']
        unique_together = ['site', 'name']

    def __str__(self):
        return self.name


class Organisation(BaseModel, SitesMixin):
    name = models.CharField(max_length=255, unique=True)
    short_name = models.CharField(max_length=50, unique=True)
    country = CountryField()
    ror = models.CharField('ROR Id', max_length=9, null=True, blank=True)
    people = models.ManyToManyField(Person, blank=True, related_name='organisations')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Group(BaseModel, SiteMixin):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    people = models.ManyToManyField(Person, blank=True, related_name='groups')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Contributor(BaseModel):
    person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='contributes_to_resources')
    role = models.ForeignKey(PersonRole, on_delete=models.CASCADE)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.CharField(max_length=UUID_LENGTH)
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        unique_together = ['content_type', 'object_id', 'person', 'role']
        ordering = ['role__name', 'person']
        indexes = [models.Index(fields=["content_type", "object_id"])]

    def __str__(self):
        return f'{self.role.name} - {self.person.full_name}'


# -----------------------------------------------------------------------------
# Resources

class ResourceStatus(BaseModel, SiteMixin):
    position = models.PositiveIntegerField(default=0)
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['position']
        verbose_name_plural = 'Resource statuses'
        unique_together = ['site', 'name']

    def __str__(self):
        return self.name


class Resource(BaseModel, SiteMixin):

    class Kind(models.TextChoices):
        MATERIAL = 'MATERIAL', 'Material'
        TEST_METHOD = 'TEST_METHOD', 'Test method'
        PROTOCOL_SOP = 'PROTOCOL_SOP', 'Protocol or SOP'
        DATA = 'DATA', 'Data'

    archived = models.BooleanField(
        default=False,
        help_text='If checked, this resource will not be shown in the registry by default. It will still be accessible if requested.'
    )

    name = models.CharField(max_length=255)
    kind = models.CharField('Type of resource', max_length=100, choices=Kind.choices)
    description = models.TextField(null=True, blank=True)

    status = models.ForeignKey(ResourceStatus, on_delete=models.PROTECT, related_name='resources')
    license = models.ForeignKey(License, on_delete=models.PROTECT, null=True, blank=True, related_name='resources')
    groups = models.ManyToManyField(Group, blank=True, related_name='resources', verbose_name='Use cases')
    contributors = GenericRelation(Contributor)

    data_link = models.URLField('Resource link', null=True, blank=True,
                                help_text='Link to the resource (e.g. Zenodo, Figshare, etc.)')

    harmonised_json = models.JSONField('Harmonised JSON data', null=True, blank=True,
                                       help_text='JSON file containing the harmonised data')

    class Meta:
        ordering = ['name', 'kind']

    def __str__(self):
        return self.name

    @property
    def organisations(self):
        return Organisation.objects.filter(
            people__contributes_to_resources__object_id=self.id,
            people__contributes_to_resources__content_type=ContentType.objects.get_for_model(Resource)
        ).distinct()

    def to_ydoc(self):
        return {
            'id': self.id,
            'name': self.name,
        }


def resource_file_path(instance, filename):
    return f'{settings.REGISTRY_RESOURCE_FILE_DIR}{instance.resource.id}/{filename}'


class ResourceFile(BaseModel):
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE, related_name='files')

    name = models.CharField(max_length=255, null=True, blank=True)
    file = models.FileField(upload_to=resource_file_path)

    class Meta:
        ordering = ['resource', 'file']

    def __str__(self):
        return os.path.basename(self.file.name)


# -----------------------------------------------------------------------------
# Study designs

class StudyDesign(BaseModel, SiteMixin):
    archived = models.BooleanField(
        default=False,
        help_text='If checked, this study design map will not be shown in the registry by default. It will still be accessible if requested.'
    )

    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    license = models.ForeignKey(License, on_delete=models.PROTECT, null=True, blank=True, related_name='study_designs')
    groups = models.ManyToManyField(Group, blank=True, related_name='study_designs', verbose_name='Use cases')
    contributors = GenericRelation(Contributor)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def to_ydoc(self):
        return {
            'nodes': dict([(node.id, node.to_ydoc()) for node in self.nodes.all()]),   # type: ignore
            'edges': dict([(edge.id, edge.to_ydoc()) for edge in self.edges.all()])    # type: ignore
        }

    def update_from_ydoc(self, scope, ydoc):
        with transaction.atomic():
            nodes_db = dict([(node.id, node) for node in self.nodes.all()])  # type: ignore
            nodes_db_set = set(nodes_db.keys())
            nodes_ydoc = ydoc.get('nodes', {})
            nodes_ydoc_set = set([node_id for node_id in nodes_ydoc.keys()])

backend/registry/api/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from rest_framework import viewsets, mixins, authentication, permissions
from rest_framework.response import Response
from rest_framework.authtoken.models import Token

from .. import models
from . import serializers


@login_required
def docs(request):
    return render(request, 'registry/api/docs.html', {
        'hostname': request.get_host(),
        'scheme': 'https' if request.is_secure() else 'http',
        'token': Token.objects.get_or_create(user=request.user)[0].key if request.user.is_authenticated else None,
    })


class AuthzMixin:
    authentication_classes = [authentication.SessionAuthentication, authentication.TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]


class ListRetrieveViewSet(
    viewsets.GenericViewSet,
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin
):
    pass


class PersonRoleViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.PersonRole.objects.none()
    serializer_class = serializers.PersonRoleSerializer

    def get_queryset(self):
        return models.PersonRole.site_objects(self.request)


class PersonViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.Person.objects.none()
    serializer_class = serializers.PersonSerializer

    def get_queryset(self):
        return models.Person.site_objects(self.request)


class GroupViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.Group.objects.none()
    serializer_class = serializers.GroupSerializer

    def get_queryset(self):
        return models.Group.site_objects(self.request)


class LicenseViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.License.objects.none()
    serializer_class = serializers.LicenseSerializer

    def get_queryset(self):
        return models.License.site_objects(self.request)


class ResourceKindViewSet(AuthzMixin, viewsets.ViewSet):
    def list(self, request):
        queryset = models.Resource.Kind
        serializer = serializers.ResourceKindSerializer(queryset, many=True)
        return Response(serializer.data)


class ResourceStatusViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.ResourceStatus.objects.none()
    serializer_class = serializers.ResourceStatusSerializer

    def get_queryset(self):
        return models.ResourceStatus.site_objects(self.request)


class ResourceViewSet(AuthzMixin, viewsets.ModelViewSet):
    queryset = models.Resource.objects.none()
    serializer_class = serializers.ResourceSerializer
    http_method_names = ['head', 'options', 'get', 'post', 'patch']

    def get_queryset(self):
        return models.Resource.site_objects(self.request).filter(archived=False)


class ResourceFileViewSet(AuthzMixin, viewsets.ModelViewSet):
    queryset = models.ResourceFile.objects.none()
    serializer_class = serializers.ResourceFileSerializer
    http_method_names = ['head', 'options', 'get', 'post', 'patch']

    def get_queryset(self):
        return models.ResourceFile.objects.filter(resource__site=self.request.site, resource__archived=False)

backend/registry/templates/registry/partials/chevron_right.html
<!-- Heroicon name: mini/chevron-right -->
<svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
    <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
</svg>

backend/registry/templates/registry/partials/contributor_formset.html
<div id="contributor-formset" class="my-2gap">
    <label class="block text-sm font-medium">Contributors</label>
    {% if formset.non_form_errors %}
    <div class="text-error text-sm">Please add at least one contributor.</div>
    {% endif %}
    <div class="forms-container mt-gap border p-gap empty:border-none">
        {% for form in formset.forms %}
        {{ form.id }}
        {{ form.non_field_errors }}
        <div class="form flex items-center space-x-1 my-gap">
            <div class="w-[45%]">{% include 'partials/form_field.html' with field=form.person %}</div>
            <div class="w-[45%]">{% include 'partials/form_field.html' with field=form.role %}</div>
            <div class="w-[7%] text-center pt-2gap">
                {% if formset.can_delete %}
                {{ form.DELETE }}
                <button type="button" class="delete-form-button"><span
                        class="material-symbols-outlined">delete</span></button>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div><input type="button" class="add-form-button cursor-pointer text-sm mt-gap" value="+ Add another contributor">
    </div>
    <template class="empty-form-template">
        <div class="form flex items-center space-x-1 mb-gap">
            <div class="w-[45%]">{% include 'partials/form_field.html' with field=formset.empty_form.person %}</div>
            <div class="w-[45%]">{% include 'partials/form_field.html' with field=formset.empty_form.role %}
            </div>
            <div class="w-[7%] text-center pt-2gap">
                {% if formset.can_delete %}
                <button type="button" class="delete-form-button"><span class="material-symbols-outlined">delete</span></button>
                {% endif %}
            </div>
        </div>
    </template>
    {{ formset.management_form }}
</div>

<script defer>
    new ConvenientFormset({
        'formsetPrefix': '{{ formset.prefix }}',
        'formsContainerSelector': '#contributor-formset .forms-container',
        'formSelector': '.form',

        'canAddForms': true,
        'addFormButtonSelector': '#contributor-formset .add-form-button',
        'emptyFormTemplateSelector': '#contributor-formset .empty-form-template',

        'canDeleteForms': true,
        'deleteFormButtonSelector': '.delete-form-button',

        'canOrderForms': false,
    })
</script>

backend/registry/templates/registry/partials/json_measurement_data.html
    {% for data in data_points %}
    <table class="table table-fixed mt-2gap w-full">
        <tr class="border-b">
        {% for key,value in data.items %}
            {% if key != 'Provenance' %}
            <th class="text-left align-top pr-gap">{{ key }}</th>
            {% endif %}
        {% endfor %}
            <th class="text-left align-top pr-gap">Provenance</th>
        </tr>
        <tr>
        {% for key,value in data.items %}
        {% if key != 'Provenance' %}
            <td class="align-top">
                {{ value }}
            </td>
        {% endif %}
        {% endfor %}
            <td>
            {% if data.Provenance %}
            {% include './json_value_provenance.html' with source=data.Provenance %}
            {% else %}
            /
            {% endif %}
            </td>
        </tr>
    </table>
    {% endfor %}

backend/registry/templates/registry/partials/json_value.html
{% if items.Provenance %}
    <tr>
        <td>
            {% if items.Value %}
            <div class="flex items-center relative">
                <span>{{ items.Value|linebreaks|safe }}</span>
                {% include './json_value_provenance.html' with source=items.Provenance %}
            </div>
            {% else %}
            /
            {% endif %}
        </td>
    </tr>
{% else %}
    {% for key, value in items.items %}
    <tr>
    <td>
        <table>
            <tr>
                <td class="align-top w-[250px]">{{ key }}:</td>
                <td><table>{% include 'registry/partials/json_value.html' with items=value %}</table></td>
            </tr>
        </table>
    </td>
    </tr>
    {% endfor %}
{% endif %}

backend/registry/templates/registry/partials/json_value_provenance.html
<div class="cursor-pointer ml-2 mt-1 relative inline-block" _="on click toggle .hidden on .provenance in me">
    <span class="material-symbols-outlined">info</span>
    <div class="provenance hidden text-sm bg-white border p-gap absolute top-2gap -left-[200px] z-10 w-[350px]">
        <span class="material-symbols-outlined absolute top-2 right-2">close</span>
        <div class="font-bold">Provenance</div>
        <div>Source: {{ source.Source }}</div>
        <div>Access date: {{ source.AccessDate }}</div>
        <div>Original source: {{ source.LinkOriginal }}</div>
        <div>Extracted data: {{ source.LinkExtracted }}</div>
    </div>
</div>

backend/registry/templates/registry/partials/resource_file_formset.html
<div id="resource-file-formset" class="my-2gap">
    <label class="block text-sm font-medium">Resource files</label>
    <div class="forms-container mt-gap border p-gap empty:border-none">
        {% for form in formset.forms %}
        {{ form.id }}
        {{ form.non_field_errors }}
        <div class="form flex items-start space-x-1 my-gap">
            <div class="w-[45%]">{% include 'partials/form_field.html' with field=form.name %}</div>
            <div class="w-[45%]">{% include 'partials/form_field.html' with field=form.file %}</div>
            <div class="w-[7%] text-center pt-2gap">
                {% if formset.can_delete %}
                {{ form.DELETE }}
                <button type="button" class="delete-form-button"><span
                        class="material-symbols-outlined">delete</span></button>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div><input type="button" class="add-form-button cursor-pointer text-sm mt-gap" value="+ Add another resource file">
    </div>
    <template class="empty-form-template">
        <div class="form flex items-start space-x-1 mb-gap">
            <div class="w-[45%]">{% include 'partials/form_field.html' with field=formset.empty_form.name %}</div>
            <div class="w-[45%]">{% include 'partials/form_field.html' with field=formset.empty_form.file %}
            </div>
            <div class="w-[7%] text-center pt-2gap">
                {% if formset.can_delete %}
                <button type="button" class="delete-form-button"><span class="material-symbols-outlined">delete</span></button>
                {% endif %}
            </div>
        </div>
    </template>
    {{ formset.management_form }}
</div>

<script defer>
    new ConvenientFormset({
        'formsetPrefix': '{{ formset.prefix }}',
        'formsContainerSelector': '#resource-file-formset .forms-container',
        'formSelector': '.form',

        'canAddForms': true,
        'addFormButtonSelector': '#resource-file-formset .add-form-button',
        'emptyFormTemplateSelector': '#resource-file-formset .empty-form-template',

        'canDeleteForms': true,
        'deleteFormButtonSelector': '.delete-form-button',

        'canOrderForms': false,
    })
</script>

backend/registry/templates/registry/partials/resource_form.html
<div class="space-y-2gap mb-2gap">
    {% include 'partials/form_field.html' with field=form.name %}
    {% include 'partials/form_field.html' with field=form.kind %}
    {% include 'partials/form_field.html' with field=form.description %}
    {% include 'partials/form_field.html' with field=form.status %}
    {% include 'partials/form_field.html' with field=form.license %}
    {% include 'partials/form_field.html' with field=form.groups %}
    {% include 'partials/form_field.html' with field=form.data_link %}
</div>

backend/registry/templates/registry/partials/resources.html
{% if not resources %}
<div class="my-3gap">No resources found for selected parameters.</div>
{% else %}
<div class="overflow-x-auto">
    <table class="min-w-full w-full divide-y divide-gray-300">
        <thead>
            <tr>
                <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold">Name</th>
                <th scope="col" class="w-[160px] py-3.5 px-3 text-left text-sm font-semibold">Type</th>
                <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold whitespace-nowrap">Use cases</th>
                <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold">Organisation</th>
                <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold">Status</th>
            </tr>
        </thead>

        <tbody class="divide-y divide-gray-200">
            {% for resource in resources %}
            <tr>
                <td class="whitespace-nowrap py-4 px-3 text-sm truncate"><a href="{% url 'registry:resource' resource.id %}">{{ resource.name }}</a></td>
                <td class="whitespace-nowrap py-4 px-3 text-sm text-muted"><span class="mt-3 text-sm px-1 rounded-sm">{{ resource.get_kind_display }}</span></td>
                <td class="whitespace-nowrap py-4 px-3 text-sm truncate text-muted">{% if resource.groups.all %}<span class="truncate">{% for group in resource.groups.all %}{{ group }}{% if not forloop.last %}, {% endif %}{% endfor %}</span>{% endif %}</td>
                <td class="whitespace-nowrap py-4 px-3 text-sm truncate text-muted">
                    {% for organisation in resource.organisations %}
                    {{ organisation.short_name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
                <td class="py-4 px-3 text-sm text-muted"><span class="truncate">{{ resource.status }}</span></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

backend/registry/templates/registry/partials/study_design_form.html
<div class="space-y-2gap mb-2gap">
    {% include 'partials/form_field.html' with field=form.name %}
    {% include 'partials/form_field.html' with field=form.description %}
    {% include 'partials/form_field.html' with field=form.instance_map_link %}
    {% include 'partials/form_field.html' with field=form.license %}
    {% include 'partials/form_field.html' with field=form.groups %}
</div>

backend/registry/templates/registry/partials/study_design_header.html
<div>
    <div>
        <h1>
            <div class="mb-1">Study design</div>
            <div class="text-lg leading-normal">{{ study_design.name }}</div>
        </h1>
    </div>

    <div class="mt-0 text-right">
        <a href="{% url 'registry:study_design_map' study_design.id %}" class="{% if active_view == 'map' %}border-b-4 border-primary-400{% endif %} inline-block !no-underline px-gap pb-1/2gap">Map</a>
        <a href="{% url 'registry:study_design' study_design.id %}" class="{% if active_view == 'general-info' %}border-b-4 border-primary-400{% endif %} inline-block !no-underline px-gap pb-1/2gap">General info</a>
    </div>
</div>

backend/registry/templates/registry/partials/study_designs.html
{% if not study_designs %}
<div class="my-3gap">No study designs found.</div>
{% else %}
<div class="overflow-x-auto">
    <table class="min-w-full w-full divide-y divide-gray-300">
        <thead>
            <tr>
                <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold">Name</th>
                <th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold">Use cases</th>
            </tr>
        </thead>

        <tbody class="divide-y divide-gray-200">
            {% for study_design in study_designs %}
            <tr>
                <td class="whitespace-nowrap py-4 px-3 text-sm truncate"><a href="{% url 'registry:study_design_map' study_design.id %}">{{ study_design.name }}</a></td>
                <td class="whitespace-nowrap py-4 px-3 text-sm">
                    {% for group in study_design.groups.all %}
                    <div>{{ group.name }}</div>
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}