backend/registry/api/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'people', views.PersonViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'licenses', views.LicenseViewSet)
router.register(r'person-roles', views.PersonRoleViewSet)
router.register(r'resource-kinds', views.ResourceKindViewSet, basename='resourcekind')
router.register(r'resource-statuses', views.ResourceStatusViewSet)
router.register(r'resources', views.ResourceViewSet)
router.register(r'resource-files', views.ResourceFileViewSet)

urlpatterns = [
    path('docs/', views.docs, name='api_docs'),
    path('', include(router.urls)),
]

backend/registry/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('people/', views.people, name='people'),
    path('people/<slug:person_id>/', views.person, name='person'),
    path('organisations/', views.organisations, name='organisations'),
    path('organisations/<slug:organisation_id>/', views.organisation, name='organisation'),
    path('groups/', views.groups, name='groups'),
    path('groups/<slug:group_id>/', views.group, name='group'),
    path('licenses/', views.licenses, name='licenses'),
    path('licenses/<slug:license_id>/', views.license, name='license'),
    path('resources/', views.resources, name='resources'),
    path('resources/add/', views.resource_add, name='resource_add'),
    path('resources/<slug:resource_id>/', views.resource, name='resource'),
    path('resources/<slug:resource_id>/edit/', views.resource_edit, name='resource_edit'),
    path('study-designs/', views.study_designs, name='study_designs'),
    path('study-designs/add/', views.study_design_add, name='study_design_add'),
    path('study-designs/<slug:study_design_id>/', views.study_design, name='study_design'),
    path('study-designs/<slug:study_design_id>/edit/', views.study_design_edit, name='study_design_edit'),
    path('study-designs/<slug:study_design_id>/map/', views.study_design_map, name='study_design_map'),
]

backend/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from decorator_include import decorator_include

import backend.registry.urls
import backend.registry.media
import backend.registry.consumers
from backend.auth import site_member_required, CustomPasswordResetView

admin.site.site_title = "Registry Administration"
admin.site.site_header = "Registry Administration"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('backend.registry.api.urls')),
    path('media/<path:path>', backend.registry.media.check_access),
    path('', decorator_include([login_required, site_member_required], (backend.registry.urls, 'registry'), namespace='registry')),  # type: ignore
] + debug_toolbar_urls()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websocket_urlpatterns = [
    path('ws/registry/study-design-maps/<str:study_design_id>', backend.registry.consumers.YjsConsumer.as_asgi()),  # type: ignore
]

backend/registry/models.py
import os
import shortuuid

from django.conf import settings
from django.db import models, transaction
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.sites.models import Site

from django_countries.fields import CountryField

from backend.utils import get_current_site

UUID_LENGTH = 12


# -----------------------------------------------------------------------------
# Utils

def uuid():
    # Keep the alphabet and length in sync with the one on the frontend (studyDesignMaps/shortUUID.ts)
    su = shortuuid.ShortUUID(alphabet='23456789abcdefghjklmnpqrstuvwxyz')
    return su.random(length=UUID_LENGTH)


class BaseModel(models.Model):
    id = models.CharField(primary_key=True, max_length=UUID_LENGTH, default=uuid, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# -----------------------------------------------------------------------------
# Project

class Project(BaseModel):
    site = models.OneToOneField(Site, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    logo = models.ImageField(null=True, blank=True, upload_to='projects/logos')
    style = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['site__name']

    def __str__(self):
        return str(self.site)

    @property
    def domain(self):
        return self.site.domain

    @property
    def name(self):
        return self.site.name

    def save(self, *args, **kwargs):
        if self._state.adding:
            for (pos, type) in enumerate(settings.REGISTRY_DEFAULT_NODE_TYPES):
                StudyDesignNodeType.objects.create(
                    site=self.site,
                    name=type['name'],
                    color=type['color'],
                    description=type.get('description', ''),
                    position=pos
                )
        super().save(*args, **kwargs)


class SiteMixin(models.Model):
    site = models.ForeignKey(Site, on_delete=models.CASCADE)

    class Meta:
        abstract = True

    @classmethod
    def site_objects(cls, request):
        return cls.objects.filter(site=get_current_site(request))


class SitesMixin(models.Model):
    sites = models.ManyToManyField(Site, blank=True)

    class Meta:
        abstract = True

    @classmethod
    def site_objects(cls, request):
        return cls.objects.filter(sites=get_current_site(request))


# -----------------------------------------------------------------------------
# Licenses

class License(BaseModel, SitesMixin):
    name = models.CharField(max_length=255)
    url = models.URLField('URL', null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        if self.description:
            return f'{self.name} - {self.description}'
        else:
            return self.name


# -----------------------------------------------------------------------------
# People and groups

class Person(BaseModel, SitesMixin):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    orcid = models.CharField('ORCID Id', max_length=19, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'People'
        ordering = ['user__first_name', 'user__last_name']

    def __str__(self):
        return self.full_name

    @property
    def email(self):
        return self.user.email

    @property
    def first_name(self):
        return self.user.first_name

    @property
    def last_name(self):
        return self.user.last_name

    @property
    def full_name(self):
        return self.user.get_full_name() if self.user.get_full_name() else self.user.username

    @property
    def orcid_url(self):
        if self.orcid is not None:
            return f'https://orcid.org/{self.orcid}'
        else:
            return None


class PersonRole(BaseModel, SiteMixin):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['name']
        unique_together = ['site', 'name']

    def __str__(self):
        return self.name


class Organisation(BaseModel, SitesMixin):
    name = models.CharField(max_length=255, unique=True)
    short_name = models.CharField(max_length=50, unique=True)
    country = CountryField()
    ror = models.CharField('ROR Id', max_length=9, null=True, blank=True)
    people = models.ManyToManyField(Person, blank=True, related_name='organisations')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Group(BaseModel, SiteMixin):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    people = models.ManyToManyField(Person, blank=True, related_name='groups')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Contributor(BaseModel):
    person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='contributes_to_resources')
    role = models.ForeignKey(PersonRole, on_delete=models.CASCADE)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.CharField(max_length=UUID_LENGTH)
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        unique_together = ['content_type', 'object_id', 'person', 'role']
        ordering = ['role__name', 'person']
        indexes = [models.Index(fields=["content_type", "object_id"])]

    def __str__(self):
        return f'{self.role.name} - {self.person.full_name}'


# -----------------------------------------------------------------------------
# Resources

class ResourceStatus(BaseModel, SiteMixin):
    position = models.PositiveIntegerField(default=0)
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['position']
        verbose_name_plural = 'Resource statuses'
        unique_together = ['site', 'name']

    def __str__(self):
        return self.name


class Resource(BaseModel, SiteMixin):

    class Kind(models.TextChoices):
        MATERIAL = 'MATERIAL', 'Material'
        TEST_METHOD = 'TEST_METHOD', 'Test method'
        PROTOCOL_SOP = 'PROTOCOL_SOP', 'Protocol or SOP'
        DATA = 'DATA', 'Data'

    archived = models.BooleanField(
        default=False,
        help_text='If checked, this resource will not be shown in the registry by default. It will still be accessible if requested.'
    )

    name = models.CharField(max_length=255)
    kind = models.CharField('Type of resource', max_length=100, choices=Kind.choices)
    description = models.TextField(null=True, blank=True)

    status = models.ForeignKey(ResourceStatus, on_delete=models.PROTECT, related_name='resources')
    license = models.ForeignKey(License, on_delete=models.PROTECT, null=True, blank=True, related_name='resources')
    groups = models.ManyToManyField(Group, blank=True, related_name='resources', verbose_name='Use cases')
    contributors = GenericRelation(Contributor)

    data_link = models.URLField('Resource link', null=True, blank=True,
                                help_text='Link to the resource (e.g. Zenodo, Figshare, etc.)')

    harmonised_json = models.JSONField('Harmonised JSON data', null=True, blank=True,
                                       help_text='JSON file containing the harmonised data')

    class Meta:
        ordering = ['name', 'kind']

    def __str__(self):
        return self.name

    @property
    def organisations(self):
        return Organisation.objects.filter(
            people__contributes_to_resources__object_id=self.id,
            people__contributes_to_resources__content_type=ContentType.objects.get_for_model(Resource)
        ).distinct()

    def to_ydoc(self):
        return {
            'id': self.id,
            'name': self.name,
        }


def resource_file_path(instance, filename):
    return f'{settings.REGISTRY_RESOURCE_FILE_DIR}{instance.resource.id}/{filename}'


class ResourceFile(BaseModel):
    resource = models.ForeignKey(Resource, on_delete=models.CASCADE, related_name='files')

    name = models.CharField(max_length=255, null=True, blank=True)
    file = models.FileField(upload_to=resource_file_path)

    class Meta:
        ordering = ['resource', 'file']

    def __str__(self):
        return os.path.basename(self.file.name)


# -----------------------------------------------------------------------------
# Study designs

class StudyDesign(BaseModel, SiteMixin):
    archived = models.BooleanField(
        default=False,
        help_text='If checked, this study design map will not be shown in the registry by default. It will still be accessible if requested.'
    )

    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    license = models.ForeignKey(License, on_delete=models.PROTECT, null=True, blank=True, related_name='study_designs')
    groups = models.ManyToManyField(Group, blank=True, related_name='study_designs', verbose_name='Use cases')
    contributors = GenericRelation(Contributor)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def to_ydoc(self):
        return {
            'nodes': dict([(node.id, node.to_ydoc()) for node in self.nodes.all()]),   # type: ignore
            'edges': dict([(edge.id, edge.to_ydoc()) for edge in self.edges.all()])    # type: ignore
        }

    def update_from_ydoc(self, scope, ydoc):
        with transaction.atomic():
            nodes_db = dict([(node.id, node) for node in self.nodes.all()])  # type: ignore
            nodes_db_set = set(nodes_db.keys())
            nodes_ydoc = ydoc.get('nodes', {})
            nodes_ydoc_set = set([node_id for node_id in nodes_ydoc.keys()])

backend/registry/api/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from rest_framework import viewsets, mixins, authentication, permissions
from rest_framework.response import Response
from rest_framework.authtoken.models import Token

from .. import models
from . import serializers


@login_required
def docs(request):
    return render(request, 'registry/api/docs.html', {
        'hostname': request.get_host(),
        'scheme': 'https' if request.is_secure() else 'http',
        'token': Token.objects.get_or_create(user=request.user)[0].key if request.user.is_authenticated else None,
    })


class AuthzMixin:
    authentication_classes = [authentication.SessionAuthentication, authentication.TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]


class ListRetrieveViewSet(
    viewsets.GenericViewSet,
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin
):
    pass


class PersonRoleViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.PersonRole.objects.none()
    serializer_class = serializers.PersonRoleSerializer

    def get_queryset(self):
        return models.PersonRole.site_objects(self.request)


class PersonViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.Person.objects.none()
    serializer_class = serializers.PersonSerializer

    def get_queryset(self):
        return models.Person.site_objects(self.request)


class GroupViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.Group.objects.none()
    serializer_class = serializers.GroupSerializer

    def get_queryset(self):
        return models.Group.site_objects(self.request)


class LicenseViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.License.objects.none()
    serializer_class = serializers.LicenseSerializer

    def get_queryset(self):
        return models.License.site_objects(self.request)


class ResourceKindViewSet(AuthzMixin, viewsets.ViewSet):
    def list(self, request):
        queryset = models.Resource.Kind
        serializer = serializers.ResourceKindSerializer(queryset, many=True)
        return Response(serializer.data)


class ResourceStatusViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.ResourceStatus.objects.none()
    serializer_class = serializers.ResourceStatusSerializer

    def get_queryset(self):
        return models.ResourceStatus.site_objects(self.request)


class ResourceViewSet(AuthzMixin, viewsets.ModelViewSet):
    queryset = models.Resource.objects.none()
    serializer_class = serializers.ResourceSerializer
    http_method_names = ['head', 'options', 'get', 'post', 'patch']

    def get_queryset(self):
        return models.Resource.site_objects(self.request).filter(archived=False)


class ResourceFileViewSet(AuthzMixin, viewsets.ModelViewSet):
    queryset = models.ResourceFile.objects.none()
    serializer_class = serializers.ResourceFileSerializer
    http_method_names = ['head', 'options', 'get', 'post', 'patch']

    def get_queryset(self):
        return models.ResourceFile.objects.filter(resource__site=self.request.site, resource__archived=False)

backend/registry/templates/registry/license.html
{% extends 'base.html' %}

{% block title %}{{ license }}{% endblock %}

{% block body %}

<div class="container">

    <h1>{{ license }}</h1>

    <dl>
        <div>
            <dt>ID</dt>
            <dd class="!text-base font-mono">{{ license.id }}</dd>
        </div>

        <div>
            <dt>Name</dt>
            <dd>
                {{ license.name }}
            </dd>
        </div>

        <div>
            <dt>URL</dt>
            <dd>
                {% if license.url %}
                <a href="{{ license.url }}">{{ license.url }}</a>
                {% else %}
                /
                {% endif %}
            </dd>
        </div>

        {% if license.description %}
        <div>
            <dt>Description</dt>
            <dd>
                {{ license.description }}
            </dd>
        </div>
        {% endif %}

        <div>
            <dt>Resources</dt>
            <dd>
                {% if resources %}
                <ul>
                    {% for resource in resources %}
                    <li><a href="{% url 'registry:resource' resource.id %}">{{ resource }}</a></li>
                    {% endfor %}
                </ul>
                {% else %}
                /
                {% endif %}
            </dd>
        </div>
    </dl>
</div>

{% endblock %}

backend/registry/templates/registry/resource.html
{% extends 'base.html' %}

{% load markdownify %}

{% block title %}{{ resource }}{% endblock %}

{% block body %}

<div class="container">
    <div class="flex justify-between items-center">
        <h1>
            <div class="mb-1">Resource</div>
            <div class="text-lg leading-normal">{{ resource.name }}</div>
        </h1>
        <a class="btn btn-primary whitespace-nowrap ml-gap" href="{% url 'registry:resource_edit' resource.id %}">Update this resource</a>
    </div>

    <dl>
        <div>
            <dt>ID</dt>
            <dd class="!text-base font-mono">{{ resource.id }}</dd>
        </div>

        <div>
            <dt>Name</dt>
            <dd>{{ resource.name }}</dd>
        </div>

        {% if resource.archived %}
        <div class="bg-yellow-50">
            <dt>Archived</dt>
            <dd>
                <h3 class="text-sm font-medium text-yellow-800">Please note!</h3>
                This resource is archived.
                <br>Update it if you need to un-archive it.
            </dd>
        </div>
        {% endif %}

        <div>
            <dt>Type of resource</dt>
            <dd>{{ resource.get_kind_display }}</dd>
        </div>

        <div>
            <dt>Status</dt>
            <dd>{{ resource.status }}</dd>
        </div>

        <div>
            <dt>Description</dt>
            <dd>
                {% if resource.description %}
                {{ resource.description|markdownify }}
                {% else %}
                /
                {% endif %}
            </dd>
        </div>

        <div>
            <dt>Use cases</dt>
            <dd>
                {% if resource.groups.all.count %}
                <ul>
                    {% for group in resource.groups.all %}
                    <li><a href="{% url 'registry:group' group.id %}">{{ group }}</a></li>
                    {% endfor %}
                </ul>
                {% else %}
                /
                {% endif %}
            </dd>
        </div>

        <div>
            <dt>Contributors</dt>
            <dd>
                {% if resource.contributors.all.count %}
                <ul>
                    {% for contributor in resource.contributors.all %}
                    <li><a href="{% url 'registry:person' contributor.person.id %}">{{ contributor.person.full_name }}</a>, <span class="text-muted">{{ contributor.role.name }}</span></li>
                    {% endfor %}
                </ul>
                {% else %}
                /
                {% endif %}
            </dd>
        </div>

        <div>
            <dt>License</dt>
            <dd>
                {% if resource.license %}
                <a href="{% url 'registry:license' resource.license.id %}">{{ resource.license.name }}</a>{% if resource.license.description %}, <span class="text-muted">{{ resource.license.description }}{% endif %}</span>
                {% else %}
                /
                {% endif %}
            </dd>
        </div>
    </dl>

    {% if resource.data_link or resource.files.all %}
    <div class="border-t pt-2gap pb-3gap">
        <h3>Resource files</h3>

        <ul class="list-disc list-inside space-y-2">
            {% if resource.data_link %}
                <li class="text-ellipsis overflow-hidden ..."><a class="" href="{{ resource.data_link }}">{{ resource.data_link }}</a></li>
            {% endif %}
            {% if resource.files.all %}
                {% for file in resource.files.all %}
                {% if not file.archived %}
                <li class="text-ellipsis overflow-hidden ...">
                    <a href="{{ file.file.url }}">{{ file }}</a> {% if file.name %}&ndash; {{ file.name }}{% endif %}
                </li>
                {% endif %}
                {% endfor %}
            {% endif %}
        </ul>
    </div>
    {% endif %}

    {% if resource.harmonised_json %}
    <div class="border px-2gap py-gap">
        <h3>Properties</h3>
        {% if resource.kind == "MATERIAL" %}
            <div class="flex justify-between items-center">
                <table>
                    {% if resource.harmonised_json.InternalId %}
                    <tr>
                        <td class="w-[120px]">Internal id:</td>
                        <td><table>{% include './partials/json_value.html' with items=resource.harmonised_json.InternalId %}</table></td>
                    </tr>
                    {% endif %}

                    {% if resource.harmonised_json.MaterialType %}
                    <tr>
                        <td class="w-[120px]">MaterialType:</td>
                        <td><table>{% include './partials/json_value.html' with items=resource.harmonised_json.MaterialType %}</table></td>
                    </tr>
                    {% endif %}
                </table>
                <div class="bg-black text-white rounded-full text-center align-center w-[40px] h-[40px] leading-[50px] cursor-pointer"><span class="material-symbols-outlined">download</span></div>
            </div>

            {% if resource.harmonised_json.Properties %}
            <div class="bg-gray-100 p-2 -mx-2 font-bold mt-2gap mb-gap cursor-pointer flex justify-between items-center" _="on click toggle .hidden on #properties then toggle .hidden on .material-symbols-outlined in me">
                <div>Properties</div>
                <span class="material-symbols-outlined">expand_more</span>
                <span class="material-symbols-outlined hidden">expand_less</span>
            </div>

            <div id="properties" class="hidden">
                {% for key,value in resource.harmonised_json.Properties.items %}
                <p><b>{{ key }}</b></p>
                <table class="mb-gap">
                {% include './partials/json_value.html' with items=value %}
                </table>
                {% endfor %}
            </div>
            {% endif %}

            {% if resource.harmonised_json.Protocol %}
            <div class="bg-gray-100 p-2 -mx-2 font-bold mt-2gap mb-gap flex justify-between items-center">
                <div>Protocol</div>
            </div>

            <div>
                <table>
                    <tr>
                        <th class="w-[120px] text-left">Registry Id:</th>
                        <td><a href="{% url 'registry:resource' resource.harmonised_json.Protocol.ProtocolId %}">{{ resource.harmonised_json.Protocol.ProtocolId }}</a></td>
                    </tr>
                    <tr>
                        <th class="w-[120px] text-left">Name:</th>
                        <td>{{ resource.harmonised_json.Protocol.ProtocolName }}</td>
                    </tr>
                </table>
                {% if resource.harmonised_json.Protocol.SpecialConditions %}
                <p class="my-gap"><b>Conditions</b></p>
                <table class="w-full">
                {% for condition in resource.harmonised_json.Protocol.SpecialConditions %}
                {% if forloop.counter == 1 %}
                <tr>
                {% for key,value in condition.items %}
                    <th class="{% if forloop.counter == 1 %}text-left{% else %}text-right{% endif %} text-sm border-b border-gray-300">{{ key }}</th>
                {% endfor %}
                </tr>
                {% endif %}
                {% for key,value in condition.items %}
                <td class="{% if forloop.counter == 1 %}text-left{% else %}text-right{% endif %}">
                    {% if key == 'Provenance' %}
                    {% include './partials/json_value_provenance.html' with source=value %}
                    {% else %}
                    {{ value }}
                    {% endif %}
                </td>
                {% endfor %}
                </tr>
                {% endfor %}
                </table>
                {% endif %}
            </div>
            {% endif %}

            {% if resource.harmonised_json.ChemicalComponents %}
            <div class="bg-gray-100 p-2 -mx-2 font-bold mt-2gap mb-gap flex justify-between items-center">
                <div>Chemical components</div>
            </div>

            <div>
                <table class="w-full">
                {% for component in resource.harmonised_json.ChemicalComponents %}
                {% if forloop.counter == 1 %}
                <tr>
                    <th class="text-left">Component</th>
                    {% for parameter in component.parameters %}
                    <th class="text-right">{{ parameter.Name }}</th>
                    {% endfor %}
                </tr>
                {% endif %}
                <tr>
                    <td>{{ component.name }}</td>
                    {% for parameter in component.parameters %}
                        <td class="">
                            <div class="flex items-center justify-end">
                                <span>{{ parameter.Value }} {{ parameter.Unit }}</span>
                                {% include './partials/json_value_provenance.html' with source=parameter.Provenance %}
                            </div>
                        </td>
                    {% endfor %}
                </tr>
                {% endfor %}
                </table>
            </div>
            {% endif %}

            {% if resource.harmonised_json.SafetyAssessment %}
            <div class="bg-gray-100 p-2 -mx-2 font-bold mt-2gap mb-gap cursor-pointer flex justify-between items-center" _="on click toggle .hidden on #safety-assessment then toggle .hidden on .material-symbols-outlined in me">
                <div class="flex justify-start">Safety Assessment</div>
                <span class="material-symbols-outlined">expand_more</span>
                <span class="material-symbols-outlined hidden">expand_less</span>
            </div>

            <div id="safety-assessment" class="hidden">
                {% for key,value in resource.harmonised_json.SafetyAssessment.items %}
                <p><b>{{ key }}</b></p>
                <table class="mb-gap">
                {% include './partials/json_value.html' with items=value %}
                </table>
                {% endfor %}
            </div>
            {% endif %}
        {% elif resource.kind == "PROTOCOL_SOP" %}
            <div class="flex justify-between items-center">
                <table>
                    {% if resource.harmonised_json.InternalId %}
                    <tr>
                        <td class="w-[120px]">Internal id:</td>
                        <td><table>{% include './partials/json_value.html' with items=resource.harmonised_json.InternalId %}</table></td>
                    </tr>
                    {% endif %}
                </table>
                <div class="bg-black text-white rounded-full text-center align-center w-[40px] h-[40px] leading-[50px] cursor-pointer"><span class="material-symbols-outlined">download</span></div>
            </div>

            {% if resource.harmonised_json.Steps %}
            {% for step in resource.harmonised_json.Steps %}
            <div class="bg-gray-100 p-2 -mx-2 font-bold mt-2gap mb-gap cursor-pointer flex justify-between items-center">
                <div>Step {{ forloop.counter }}</div>
            </div>

            <table>
                {% for key,value in step.items %}
                <tr>
                    <th class="text-left align-top pr-gap">{{ key }}</th>
                    <td class="align-top">
                        <table class="">
                        {% include './partials/json_value.html' with items=value %}
                        </table>
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% endfor %}
            {% endif %}

        {% elif resource.kind == "DATA" %}
            <div class="flex justify-between items-center">
                <table>
                    {% if resource.harmonised_json.InternalId %}
                    <tr>
                        <td class="w-[120px]">Internal id:</td>
                        <td><table>{% include './partials/json_value.html' with items=resource.harmonised_json.InternalId %}</table></td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td class="w-[120px]">Protocol:</td>
                        <td><a href="{% url 'registry:resource' resource.harmonised_json.Protocol %}">{{ resource.harmonised_json.Protocol }}</a></td>
                    </tr>
                    <tr>
                        <td class="w-[120px]">Material:</td>
                        <td><a href="{% url 'registry:resource' resource.harmonised_json.Material %}">{{ resource.harmonised_json.Material }}</a></td>
                    </tr>
                </table>
                <div class="bg-black text-white rounded-full text-center align-center w-[40px] h-[40px] leading-[50px] cursor-pointer"><span class="material-symbols-outlined">download</span></div>
            </div>

            {% if resource.harmonised_json.Data %}
            {% include './partials/json_measurement_data.html' with data_points=resource.harmonised_json.Data %}
            {% endif %}

        {% endif %}
    </div>
    {% endif %}

</div>

{% endblock %}

backend/registry/templates/registry/study_designs.html
{% extends 'base.html' %}

{% load backend %}

{% block title %}Study designs{% endblock %}

{% block body %}
<div class="container">
    <div class="flex justify-between items-center">
        <h1>Study designs</h1>
        <a class="btn btn-primary" href="{% url 'registry:study_design_add' %}">Register a new study design</a>
    </div>

    <div id="content">
        {% include './partials/study_designs.html' %}
    </div>
</div>
{% endblock %}