backend/registry/api/urls.py
from django.urls import include, path
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'people', views.PersonViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'licenses', views.LicenseViewSet)
router.register(r'person-roles', views.PersonRoleViewSet)
router.register(r'resource-kinds', views.ResourceKindViewSet, basename='resourcekind')
router.register(r'resource-statuses', views.ResourceStatusViewSet)
router.register(r'resources', views.ResourceViewSet)
router.register(r'resource-files', views.ResourceFileViewSet)

urlpatterns = [
    path('docs/', views.docs, name='api_docs'),
    path('', include(router.urls)),
]

backend/registry/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('people/', views.people, name='people'),
    path('people/<slug:person_id>/', views.person, name='person'),
    path('organisations/', views.organisations, name='organisations'),
    path('organisations/<slug:organisation_id>/', views.organisation, name='organisation'),
    path('groups/', views.groups, name='groups'),
    path('groups/<slug:group_id>/', views.group, name='group'),
    path('licenses/', views.licenses, name='licenses'),
    path('licenses/<slug:license_id>/', views.license, name='license'),
    path('resources/', views.resources, name='resources'),
    path('resources/add/', views.resource_add, name='resource_add'),
    path('resources/<slug:resource_id>/', views.resource, name='resource'),
    path('resources/<slug:resource_id>/edit/', views.resource_edit, name='resource_edit'),
    path('study-designs/', views.study_designs, name='study_designs'),
    path('study-designs/add/', views.study_design_add, name='study_design_add'),
    path('study-designs/<slug:study_design_id>/', views.study_design, name='study_design'),
    path('study-designs/<slug:study_design_id>/edit/', views.study_design_edit, name='study_design_edit'),
    path('study-designs/<slug:study_design_id>/map/', views.study_design_map, name='study_design_map'),
]

backend/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from decorator_include import decorator_include

import backend.registry.urls
import backend.registry.media
import backend.registry.consumers
from backend.auth import site_member_required, CustomPasswordResetView

admin.site.site_title = "Registry Administration"
admin.site.site_header = "Registry Administration"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('backend.registry.api.urls')),
    path('media/<path:path>', backend.registry.media.check_access),
    path('', decorator_include([login_required, site_member_required], (backend.registry.urls, 'registry'), namespace='registry')),  # type: ignore
] + debug_toolbar_urls()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websocket_urlpatterns = [
    path('ws/registry/study-design-maps/<str:study_design_id>', backend.registry.consumers.YjsConsumer.as_asgi()),  # type: ignore
]

backend/registry/api/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from rest_framework import viewsets, mixins, authentication, permissions
from rest_framework.response import Response
from rest_framework.authtoken.models import Token

from .. import models
from . import serializers


@login_required
def docs(request):
    return render(request, 'registry/api/docs.html', {
        'hostname': request.get_host(),
        'scheme': 'https' if request.is_secure() else 'http',
        'token': Token.objects.get_or_create(user=request.user)[0].key if request.user.is_authenticated else None,
    })


class AuthzMixin:
    authentication_classes = [authentication.SessionAuthentication, authentication.TokenAuthentication]
    permission_classes = [permissions.IsAuthenticated]


class ListRetrieveViewSet(
    viewsets.GenericViewSet,
    mixins.ListModelMixin,
    mixins.RetrieveModelMixin
):
    pass


class PersonRoleViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.PersonRole.objects.none()
    serializer_class = serializers.PersonRoleSerializer

    def get_queryset(self):
        return models.PersonRole.site_objects(self.request)


class PersonViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.Person.objects.none()
    serializer_class = serializers.PersonSerializer

    def get_queryset(self):
        return models.Person.site_objects(self.request)


class GroupViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.Group.objects.none()
    serializer_class = serializers.GroupSerializer

    def get_queryset(self):
        return models.Group.site_objects(self.request)


class LicenseViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.License.objects.none()
    serializer_class = serializers.LicenseSerializer

    def get_queryset(self):
        return models.License.site_objects(self.request)


class ResourceKindViewSet(AuthzMixin, viewsets.ViewSet):
    def list(self, request):
        queryset = models.Resource.Kind
        serializer = serializers.ResourceKindSerializer(queryset, many=True)
        return Response(serializer.data)


class ResourceStatusViewSet(AuthzMixin, ListRetrieveViewSet):
    queryset = models.ResourceStatus.objects.none()
    serializer_class = serializers.ResourceStatusSerializer

    def get_queryset(self):
        return models.ResourceStatus.site_objects(self.request)


class ResourceViewSet(AuthzMixin, viewsets.ModelViewSet):
    queryset = models.Resource.objects.none()
    serializer_class = serializers.ResourceSerializer
    http_method_names = ['head', 'options', 'get', 'post', 'patch']

    def get_queryset(self):
        return models.Resource.site_objects(self.request).filter(archived=False)


class ResourceFileViewSet(AuthzMixin, viewsets.ModelViewSet):
    queryset = models.ResourceFile.objects.none()
    serializer_class = serializers.ResourceFileSerializer
    http_method_names = ['head', 'options', 'get', 'post', 'patch']

    def get_queryset(self):
        return models.ResourceFile.objects.filter(resource__site=self.request.site, resource__archived=False)

backend/registry/views.py
import functools

from django.db import transaction
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.contrib.postgres.search import SearchQuery

from . import models
from . import forms


def index(request):
    return render(request, 'registry/index.html', {
        'study_designs': models.StudyDesign.site_objects(request).filter(archived=False),
        'resources': models.Resource.site_objects(request).filter(archived=False),
        'people': models.Person.site_objects(request).all(),
        'organisations': models.Organisation.site_objects(request).all(),
        'groups': models.Group.site_objects(request).all(),
    })


def people(request):
    return render(request, 'registry/people.html', {
        'people': models.Person.site_objects(request).all().select_related('user')
    })


def person(request, person_id):
    person = get_object_or_404(models.Person.site_objects(request), pk=person_id)
    return render(request, 'registry/person.html', {
        'person': person,
        'resources': models.Resource.site_objects(request).filter(archived=False, contributors__person=person),
    })


def organisations(request):
    return render(request, 'registry/organisations.html', {
        'organisations': models.Organisation.site_objects(request).all()
    })


def organisation(request, organisation_id):
    return render(request, 'registry/organisation.html', {
        'organisation': get_object_or_404(models.Organisation.site_objects(request), pk=organisation_id)
    })


def groups(request):
    return render(request, 'registry/groups.html', {
        'groups': models.Group.site_objects(request).all()
    })


def group(request, group_id):
    group = get_object_or_404(models.Group.site_objects(request), pk=group_id)
    return render(request, 'registry/group.html', {
        'group': group,
        'resources': models.Resource.site_objects(request).filter(archived=False, groups=group),
        'study_designs': models.StudyDesign.site_objects(request).filter(archived=False, groups=group),
    })


def licenses(request):
    return render(request, 'registry/licenses.html', {
        'licenses': models.License.site_objects(request).all()
    })


def license(request, license_id):
    license = get_object_or_404(models.License.site_objects(request), pk=license_id)
    return render(request, 'registry/license.html', {
        'license': license,
        'resources': models.Resource.site_objects(request).filter(archived=False, license=license),
    })


def get_resources(request, filters=None):
    queryset = models.Resource.site_objects(request).filter(archived=False).select_related('status').prefetch_related('groups')
    if not filters:
        return queryset
    else:
        if filters.get('search'):
            REMOVE_CHARS = "()|&:*!"
            MIN_QUERY_LENGTH = 2
            query_string = filters.get('search').strip().translate({ord(i): " " for i in REMOVE_CHARS}).strip()
            tokens = [token.strip() for token in query_string.split() if len(token.strip()) >= MIN_QUERY_LENGTH]
            if tokens:
                query = functools.reduce(lambda a, b: a & b, [SearchQuery(f'{token}:*', search_type='raw') for token in tokens])
                queryset = queryset.filter(Q(id__search=query) | Q(name__search=query) | Q(description__search=query))
        if filters.get('kind'):
            queryset = queryset.filter(kind=filters.get('kind'))
        if filters.get('group'):
            queryset = queryset.filter(groups=filters.get('group'))
        if filters.get('status'):
            queryset = queryset.filter(status=filters.get('status'))
        if filters.get('organisation'):
            queryset = queryset.filter(contributors__person__in=filters.get('organisation').people.all())
        return queryset


def resources(request):
    filters_form = forms.ResourceFiltersForm(request, request.GET)

    if filters_form.is_valid():
        resources = get_resources(request, filters_form.cleaned_data)
        if request.htmx and not request.htmx.boosted:
            return render(request, 'registry/partials/resources.html', {
                'resources': resources,
                'filters_form': filters_form,
            })
    else:
        resources = get_resources(request)

    return render(request, 'registry/resources.html', {
        'resources': resources,
        'filters_form': filters_form,
    })


def resource(request, resource_id):
    resource = get_object_or_404(models.Resource.site_objects(request), pk=resource_id)

    return render(request, 'registry/resource.html', {
        'resource': resource
    })


def study_designs(request):
    return render(request, 'registry/study_designs.html', {
        'study_designs': models.StudyDesign.site_objects(request).filter(archived=False)
    })


def study_design(request, study_design_id):
    study_design = get_object_or_404(models.StudyDesign.site_objects(request), pk=study_design_id)

    return render(request, 'registry/study_design.html', {
        'study_design': study_design,
        'nodes': study_design.nodes.all().prefetch_related('resources'),  # type: ignore
    })


def study_design_map(request, study_design_id):
    # Construct full name for the user
    user = request.user
    if user.first_name or user.last_name:
        display_name = f"{user.first_name} {user.last_name}".strip()
    else:
        # Fallback to username
        username = user.username
        # If username has @, use the part before @
        if '@' in username:
            display_name = username.split('@')[0]
        else:
            display_name = username

    return render(request, 'registry/study_design_map.html', {
        'node_types': list(models.StudyDesignNodeType.site_objects(request).all().values('id', 'name', 'color', 'description')),
        'study_design': get_object_or_404(models.StudyDesign.site_objects(request), pk=study_design_id),
        'organisations': dict([(org.id, org.short_name) for org in models.Organisation.site_objects(request).all().order_by('short_name')]),
        'user_display_name': display_name,
    })


# -----------------------------------------------------------------------------
# Resource editing

@transaction.atomic
def resource_add(request):
    if request.method == 'POST':
        form = forms.ResourceForm(request, request.POST, request.FILES)
        contributor_formset = forms.ContributorFormSet(request.POST, request=request, prefix='contributors')
        file_formset = forms.ResourceFileFormSet(request.POST, request.FILES, prefix='files')
        if form.is_valid() and contributor_formset.is_valid() and file_formset.is_valid():
            resource = form.save(commit=False)
            resource.site = request.site
            resource.save()
            save_contributor_formset(contributor_formset, resource)
            save_resource_file_formset(file_formset, resource)
            messages.add_message(request, messages.SUCCESS, 'A new resource has been registered.')
            return redirect('registry:resource', resource_id=resource.id)
    else:
        form = forms.ResourceForm(request)
        contributor_formset = forms.ContributorFormSet(request=request, prefix='contributors', queryset=models.Contributor.objects.none())
        file_formset = forms.ResourceFileFormSet(prefix='files', queryset=models.ResourceFile.objects.none())

    return render(request, 'registry/resource_add.html', {
        'form': form,
        'contributor_formset': contributor_formset,
        'file_formset': file_formset,
    })


@transaction.atomic
def resource_edit(request, resource_id):
    resource = get_object_or_404(models.Resource.site_objects(request), pk=resource_id)

    if request.method == 'POST':
        form = forms.ResourceForm(request, request.POST, request.FILES, instance=resource)
        contributor_formset = forms.ContributorFormSet(request.POST, request=request, prefix='contributors')
        file_formset = forms.ResourceFileFormSet(request.POST, request.FILES, prefix='files')
        if form.is_valid() and contributor_formset.is_valid() and file_formset.is_valid():
            resource = form.save()
            save_contributor_formset(contributor_formset, resource)
            save_resource_file_formset(file_formset, resource)
            messages.add_message(request, messages.SUCCESS, 'Resource has been updated.')
            return redirect('registry:resource', resource_id=resource.id)
    else:
        form = forms.ResourceForm(request, instance=resource)
        contributor_formset = forms.ContributorFormSet(
            request=request,
            prefix='contributors',
            queryset=models.Contributor.objects.filter(
                content_type=ContentType.objects.get_for_model(models.Resource),
                object_id=resource.id))
        file_formset = forms.ResourceFileFormSet(
            prefix='files',
            queryset=models.ResourceFile.objects.filter(resource=resource))

    return render(request, 'registry/resource_edit.html', {
        'resource': resource,
        'form': form,
        'contributor_formset': contributor_formset,
        'file_formset': file_formset,
    })


# -----------------------------------------------------------------------------
# Study design editing

@transaction.atomic
def study_design_add(request):
    if request.method == 'POST':
        form = forms.StudyDesignForm(request, request.POST, request.FILES)
        contributor_formset = forms.ContributorFormSet(request.POST, request=request, prefix='contributors')
        if form.is_valid() and contributor_formset.is_valid():
            study_design = form.save(commit=False)
            study_design.site = request.site
            study_design.save()
            form.save_m2m()

backend/templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-full">
<head>
    {% load static django_vite backend %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Study design registry">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block full-title %}{{ request.site.project.name }} Registry • {% block title %}{% endblock %}{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">

    <style>
        :root {
{{ request.site.project.style|safe }}
        }
    </style>

    {% vite_hmr_client %}
    {% vite_asset 'main.js' %}
    {% vite_react_refresh %}
</head>
<body class="flex flex-col w-full h-full min-h-screen text-black {% block body_class %}{% endblock %}">
    {% block header %}
    <div class="px-gap md:px-2gap lg:px-2gap border-b py-gap">
        <div>
            <nav class="w-full flex h-9 items-center justify-between" aria-label="Global">
                <div class="flex lg:min-w-0" aria-label="Global">
                    <a href="/" class="-m-1.5 p-1.5">
                        <span class="sr-only">{{ request.site.project.name }}</span>
                        {% if request.site.project.logo %}
                        <img class="h-8" src="{{ request.site.project.logo.url }}" alt="{{ request.site.project.name }}">
                        {% endif %}
                    </a>
                </div>
                <div class="flex lg:hidden">
                    <button type="button" id="main-menu-mobile-open" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
                        <span class="sr-only">Open main menu</span>
                        <!-- Heroicon name: outline/bars-3 -->
                        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                        </svg>
                    </button>
                </div>
                <div class="hidden lg:flex lg:min-w-0 lg:justify-center lg:gap-x-8 xl:gap-x-12">
                    <a href="{% url 'registry:study_designs' %}" class="font-semibold text-zinc-800 hover:text-primary-600 border-b-4{% if request.path|startswith:'/study-designs/' %} border-primary-400{% else %} border-white{% endif %} whitespace-nowrap">Study designs</a>
                    <a href="{% url 'registry:resources' %}" class="font-semibold text-zinc-800 hover:text-primary-600 border-b-4{% if request.path|startswith:'/resources/' %} border-primary-400{% else %} border-white{% endif %}">Resources</a>
                    <a href="{% url 'registry:groups' %}" class="font-semibold text-zinc-800 hover:text-primary-600 border-b-4{% if request.path|startswith:'/groups/' %} border-primary-400{% else %} border-white{% endif %} whitespace-nowrap">Use cases</a>
                    <a href="{% url 'registry:organisations' %}" class="font-semibold text-zinc-800 hover:text-primary-600 border-b-4{% if request.path|startswith:'/organisations/' %} border-primary-400{% else %} border-white{% endif %}">Organisations</a>
                    <a href="{% url 'registry:people' %}" class="font-semibold text-zinc-800 hover:text-primary-600 border-b-4{% if request.path|startswith:'/people/' %} border-primary-400{% else %} border-white{% endif %}">People</a>
                    <a href="{% url 'api_docs' %}" class="font-semibold text-zinc-800 hover:text-primary-600 border-b-4{% if request.path|startswith:'/api/docs/' %} border-primary-400{% else %} border-white{% endif %}">API</a>
                </div>
                <div class="hidden lg:flex lg:min-w-0 lg:justify-end">
                    {% if request.user.is_authenticated %}
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="inline-block rounded-lg px-3 py-1.5 text-sm font-semibold leading-6 text-zinc-800 shadow-sm ring-1 ring-gray-900/10 hover:ring-gray-900/20">Log out</button>
                    </form>
                    {% else %}
                    <a href="{% url 'login' %}" class="inline-block rounded-lg px-3 py-1.5 text-sm font-semibold leading-6 text-zinc-800 shadow-sm ring-1 ring-gray-900/10 hover:ring-gray-900/20">Log in</a>
                    {% endif %}
                </div>
            </nav>
            <!-- Mobile menu, show/hide based on menu open state. -->
            <div role="dialog" aria-modal="true">
                <div focus="true" id="main-menu-mobile" class="fixed inset-0 z-10 overflow-y-auto bg-white px-2gap py-gap hidden">
                    <div class="flex h-9 items-center justify-between">
                        <div class="flex">
                            <a href="/" class="-m-1.5 p-1.5">
                                <span class="sr-only">{{ request.site.project.name }}</span>
                                {% if request.site.project.logo %}
                                <img class="h-8" src="{{ request.site.project.logo.url }}" alt="{{ request.site.project.name }}">
                                {% endif %}
                            </a>
                        </div>
                        <div class="flex">
                            <button type="button" id="main-menu-mobile-close" class="-m-2.5 items-center justify-center rounded-md p-2.5 text-gray-700 hidden">
                                <span class="sr-only">Close menu</span>
                                <!-- Heroicon name: outline/x-mark -->
                                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>
                    </div>
                    <div class="mt-6 flow-root">
                        <div class="-my-6 divide-y divide-gray-500/10">
                            <div class="space-y-2 py-6">
                                <a href="{% url 'registry:study_designs' %}" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-zinc-800 hover:bg-gray-400/10">Study designs</a>
                                <a href="{% url 'registry:resources' %}" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-zinc-800 hover:bg-gray-400/10">Resources</a>
                                <a href="{% url 'registry:people' %}" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-zinc-800 hover:bg-gray-400/10">People</a>
                                <a href="{% url 'registry:organisations' %}" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-zinc-800 hover:bg-gray-400/10">Organisations</a>
                                <a href="{% url 'registry:groups' %}" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-zinc-800 hover:bg-gray-400/10">Groups</a>
                                <a href="{% url 'registry:licenses' %}" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-zinc-800 hover:bg-gray-400/10">Licenses</a>
                                <a href="{% url 'api_docs' %}" class="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-zinc-800 hover:bg-gray-400/10">API</a>
                            </div>
                            <div class="py-6">
                                {% if request.user.is_authenticated %}
                                <a href="{% url 'logout' %}" class="-mx-3 block rounded-lg py-2.5 px-3 text-base font-semibold leading-6 text-zinc-800 hover:bg-gray-400/10">Logout</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
    <main class="flex flex-col flex-grow pt-gap pb-2gap [&_a]:underline [&_a]:underline-offset-2 [&_a:hover]:text-primary-600">
        {% block body %}
        {% endblock %}
    </main>
    {% include 'partials/notification.html' %}
</body>
</html>